typeset -gx XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
typeset -gx XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
typeset -gx XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
typeset -gx XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-$HOME/.xdg}
typeset -gx XDG_DESKTOP_DIR=${XDG_DESKTOP_DIR:-$HOME/Desktop}
typeset -gx XDG_DOCUMENTS_DIR=${XDG_DOCUMENTS_DIR:-$HOME/Documents}
typeset -gx XDG_DOWNLOAD_DIR=${XDG_DOWNLOAD_DIR:-$HOME/Downloads}
typeset -gx XDG_MUSIC_DIR=${XDG_MUSIC_DIR:-$HOME/Music}
typeset -gx XDG_PICTURES_DIR=${XDG_PICTURES_DIR:-$HOME/Pictures}
typeset -gx XDG_VIDEOS_DIR=${XDG_VIDEOS_DIR:-$HOME/Videos}
typeset -gx XDG_PROJECTS_DIR=${XDG_PROJECTS_DIR:-$HOME/Projects}

typeset -gx SHELL_SESSIONS_DISABLE=1

typeset -gx MANPAGER='nvim +Man!' 
typeset -gx MANWIDTH=999
typeset -gx ZDOTDIR=$HOME/.config/zsh
typeset -gx ZLE_RPROMPT_INDEX=1
typeset -U PATH path fpath

eval "$(/opt/homebrew/bin/brew shellenv)"
PATH="$HOME/bin:$PATH:/Users/noah/Library/Python/3.10/bin:"
